<?xml version="1.0" encoding="UTF-8"?>
<!--

    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

    Copyright (c) 1997-2017 Oracle and/or its affiliates. All rights reserved.

    The contents of this file are subject to the terms of either the GNU
    General Public License Version 2 only ("GPL") or the Common Development
    and Distribution License("CDDL") (collectively, the "License").  You
    may not use this file except in compliance with the License.  You can
    obtain a copy of the License at
    https://oss.oracle.com/licenses/CDDL+GPL-1.1
    or LICENSE.txt.  See the License for the specific
    language governing permissions and limitations under the License.

    When distributing the software, include this License Header Notice in each
    file and include the License file at LICENSE.txt.

    GPL Classpath Exception:
    Oracle designates this particular file as subject to the "Classpath"
    exception as provided by Oracle in the GPL Version 2 section of the License
    file that accompanied this code.

    Modifications:
    If applicable, add the following below the License Header, with the fields
    enclosed by brackets [] replaced by your own identifying information:
    "Portions Copyright [year] [name of copyright owner]"

    Contributor(s):
    If you wish your version of this file to be governed by only the CDDL or
    only the GPL Version 2, indicate your decision by adding "[Contributor]
    elects to include this software in this distribution under the [CDDL or GPL
    Version 2] license."  If you don't indicate a single choice of license, a
    recipient has the option to distribute your version of this file under
    either the CDDL, the GPL Version 2 or to extend the choice of license to
    its licensees as provided above.  However, if you add GPL Version 2 code
    and therefore, elected the GPL Version 2 license, then the option applies
    only if the new code is made subject to such option by the copyright
    holder.

-->

<descriptor since="2.0">
    <description>This is a fromwsdl doc/lit fault test</description>
    <client name="fromwsdl.fault1">
        <description>
            test nulls in fault bean
        </description>
        try{
            String in = "nullBean";
            faultPort.echo(in);
            assertTrue(false);
        }catch(Fault2Exception e){
            assertTrue(e.getFaultInfo() == null);
            assertTrue(true);
        }
    </client>
    <client name="fromwsdl.fault2">
        <description>
            test WSDL defined Fault1
        </description>
        try {
            String in = "Fault1";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (Fault1Exception e) {
            System.out.println("Expected exception received: " + e.getMessage());
            assertTrue(true);
        }
    </client>

    <client name="fromwsdl.fault3">
        <description>
            test WSDL defined Fault2
        </description>
        try {
            String in = "Fault2";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (Fault2Exception e) {
            System.out.println("Expected exception received: " + e.getMessage());
            assertTrue(true);
        }
    </client>

    <client name="fromwsdl.fault4">
        <description>
            test WSDL defined Fault3
        </description>
        try {
            String in = "Fault3";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (Fault3Exception e) {
            System.out.println("Expected exception received: " + e.getMessage());
            assertTrue(true);
        }
    </client>

    <client name="fromwsdl.fault5">
        <description>
            test WSDL defined Fault4
        </description>
        try {
            String in = "Fault4";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (Fault4Exception e) {
            System.out.println("Expected exception received: " + e.getMessage());
            assertTrue(true);
        }
    </client>

    <client name="fromwsdl.fault6">
        <description>
            test SOAPFaultException due to NPE on the server
        </description>
        try {
            String in = "NullPointerException";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (javax.xml.ws.ProtocolException e) {
            System.out.println("Expected exception received: " + e.getMessage());
            assertTrue(true);
        }
    </client>

    <client name="fromwsdl.fault7">
        <description>
            SOAPFaultException
        </description>
        try {
            String in = "SOAPFaultException";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (javax.xml.ws.ProtocolException e) {
            if (e instanceof SOAPFaultException) {
                System.out.println("Expected exception received: " + e.getMessage());
                Detail detail = ((SOAPFaultException)e).getFault().getDetail();
                assertNotNull(detail);
                Iterator i = detail.getDetailEntries();
                assertTrue(i.hasNext());
                assertEquals(((DetailEntry)i.next()).getElementQName(),
                   new QName("http://faultservice.org/wsdl", "BasicFault"));
            } else
                assertTrue(false);
        }
    </client>

    <client name="fromwsdl.fault8">
        <description>
            test SOAP fault with cause
        </description>
        try {
            String in = "Fault1-SOAPFaultException";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (Fault1Exception e) {
            System.out.println("Expected exception received: " + e.getMessage());
            assertTrue(true);
        }
    </client>

    <client name="fromwsdl.fault9">
        <description>
            test multiple details
        </description>
        try {
            faultPort.echo("multipleDetails");
        } catch (SOAPFaultException e) {
            System.out.println("Expected exception received: " + e.getMessage());
            Detail detail = e.getFault().getDetail();
            assertNotNull(detail);
            Iterator i = detail.getDetailEntries();
            assertTrue(i.hasNext());
            DetailEntry detail1 = (DetailEntry) i.next();
            assertEquals(detail1.getElementQName(),
                    new QName(
                            "http://www.example.com/faults", "myFirstDetail"));

            String val1 = detail1.getAttribute("msg");
            assertNotNull(val1);

            assertTrue(val1.equals("This is the first detail message."));

            assertTrue(i.hasNext());
            DetailEntry detail2 = (DetailEntry) i.next();
            assertEquals(detail2.getElementQName(),
                    new QName(
                            "http://www.example.com/faults", "mySecondDetail"));
            String val2 = detail2.getAttribute("msg");
            assertNotNull(val2);
            assertTrue(val2.equals("This is the second detail message."));
        }
    </client>

    <client name="fromwsdl.fault10">
        <description>
            test ProtocolException
        </description>
        try {
            String in = "ProtocolException";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (javax.xml.ws.ProtocolException e) {
            System.out.println("Expected exception received: " + e.getMessage());
            if (e.getMessage().indexOf("javax.xml.ws.ProtocolException") != -1)
                assertTrue(true);
            else
                assertTrue(false);
        }
    </client>

    <client name="fromwsdl.fault11">
        <description>
            test ProtocolException with cause
        </description>
        try {
            String in = "ProtocolException2";
            Object ret = faultPort.echo(in);
            fail("did not receive an exception");
        } catch (javax.xml.ws.ProtocolException e) {
            System.out.println("Expected exception received: " + e.getMessage());
            if (e.getMessage().indexOf("FaultImpl") != -1)
                assertTrue(true);
            else
                assertTrue(false);
        }
    </client>

    <client href="dispatch.bsh"/>
    
    <service basedir="./server">
        <wsdl href="fault.wsdl"/>
    </service>
</descriptor>
